apiVersion: v1
data:
  policy.csv: |-
    p, role:none, *, *, */*, deny
    g, image-updater, role:admin
  policy.default: role:none
  scopes: '[email]'
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
