apiVersion: v1
data:
  accounts.admin: apiKey
  application.instanceLabelKey: argocd.argoproj.io/instance
  ui.cssurl: ./custom/custom.styles.css
kind: ConfigMap
metadata:
  annotations:
      meta.helm.sh/release-name: argocd
      meta.helm.sh/release-namespace: argocd
  name: argocd-cm
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/managed-by: Helm
